= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS supporta l'archiviazione NetApp nelle seguenti configurazioni:

* FSx ONTAP come storage connesso agli ospiti
* Cloud Volumes ONTAP (CVO) come storage connesso agli ospiti
* FSx ONTAP come datastore NFS supplementare


Visualizza il dettagliolink:../vmware/vmw-aws-vmc-guest-storage.html["opzioni di archiviazione di connessione guest per VMC"] . Visualizza il dettagliolink:../vmware/vmw-aws-vmc-nfs-ds-config.html["opzioni di datastore NFS supplementari per VMC"] .

Visualizza il dettagliolink:../vmware/vmw-aws-vmc-guest-storage.html["opzioni di archiviazione di connessione guest per VMC"] . Visualizza il dettagliolink:../vmware/vmw-aws-vmc-nfs-ds-config.html["opzioni di datastore NFS supplementari per VMC"] .

--
.Azzurro / AVS
--
Azure supporta l'archiviazione NetApp nelle seguenti configurazioni:

* Azure NetApp Files (ANF) come storage connesso guest
* Cloud Volumes ONTAP (CVO) come storage connesso agli ospiti
* Azure NetApp Files (ANF) come datastore NFS supplementare


Visualizza il dettagliolink:../vmware/vmw-azure-avs-guest-storage.html["opzioni di archiviazione di connessione ospite per AVS"] . Visualizza il dettagliolink:../vmware/vmw-azure-avs-nfs-ds-config.html["opzioni di datastore NFS supplementari per AVS"] .

Visualizza il dettagliolink:../vmware/vmw-azure-avs-guest-storage.html["opzioni di archiviazione di connessione ospite per AVS"] . Visualizza il dettagliolink:../vmware/vmw-azure-avs-nfs-ds-config.html["opzioni di datastore NFS supplementari per AVS"] .

--
.GCP / GCVE
--
Google Cloud supporta l'archiviazione NetApp nelle seguenti configurazioni:

* Cloud Volumes ONTAP (CVO) come storage connesso agli ospiti
* Google Cloud NetApp Volumes (NetApp Volumes) come storage connesso agli ospiti
* Google Cloud NetApp Volumes (NetApp Volumes) come datastore NFS supplementare


Visualizza il dettagliolink:../vmware/vmw-gcp-gcve-guest-storage.html["opzioni di archiviazione per la connessione degli ospiti per GCVE"] . Visualizza il dettagliolink:../vmware/vmw-gcp-gcve-nfs-ds-overview.html["opzioni di datastore NFS supplementari per GCVE"] .

Visualizza il dettagliolink:../vmware/vmw-gcp-gcve-guest-storage.html["opzioni di archiviazione per la connessione degli ospiti per GCVE"] . Visualizza il dettagliolink:../vmware/vmw-gcp-gcve-nfs-ds-overview.html["opzioni di datastore NFS supplementari per GCVE"] .

Per saperne di piùlink:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Supporto del datastore Google Cloud NetApp Volumes per Google Cloud VMware Engine (blog NetApp )"^] Olink:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Come utilizzare Google Cloud NetApp Volumes come datastore per Google Cloud VMware Engine (blog di Google)"^]

--
====