---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-solutions.html 
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst 
summary:  
---
= Soluzioni NetApp per VMware negli Hyperscaler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri di più sulle soluzioni che NetApp offre all'ambiente VMware in ciascuno degli hyperscaler: dalla migrazione dei flussi di lavoro, all'estensione/bursting nel cloud, al backup/ripristino e al disaster recovery.



== Soluzioni NetApp per ambienti VMware

Che si operi in un modello di cloud ibrido o in un modello "cloud first", NetApp offre un'ampia gamma di soluzioni per soddisfare i casi d'uso più comuni per la gestione dei carichi di lavoro in un modello cloud o cloud ibrido.

NetApp offre anche soluzioni per l'archiviazione fornita come archiviazione in-guest (connessa all'ospite) o come datastore NFS supplementare in ciascuno degli hyperscaler.  Tutte le soluzioni sono categorizzate in base alla classificazione VMware dei carichi di lavoro cloud.  Tali classificazioni includono:

* Protezione (include sia Disaster Recovery che Backup/Ripristino)
* Migrare
* Estendere


Per maggiori dettagli sulle soluzioni disponibili per ciascun hyperscaler, visitare:

* link:vmw-aws-vmc-solutions.html["Soluzioni per AWS / VMC"]
* link:vmw-azure-avs-solutions.html["Soluzioni per Azure / AVS"]
* link:vmw-gcp-gcve-solutions.html["Soluzioni per GCP / GCVE"]

