---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-storage.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= Opzioni di archiviazione NetApp per i provider di cloud pubblico
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esplora le opzioni di NetApp come storage nei tre principali hyperscaler.

[role="tabbed-block"]
====
.AWS / VMC
--
AWS supporta l'archiviazione NetApp nelle seguenti configurazioni:

* FSx ONTAP come storage connesso agli ospiti
* Cloud Volumes ONTAP (CVO) come storage connesso agli ospiti
* FSx ONTAP come datastore NFS supplementare


Visualizza il dettagliolink:aws-guest.html["opzioni di archiviazione di connessione guest per VMC"] .  Visualizza il dettagliolink:aws-native-nfs-datastore-option.html["opzioni di datastore NFS supplementari per VMC"] .

--
.Azzurro / AVS
--
Azure supporta l'archiviazione NetApp nelle seguenti configurazioni:

* Azure NetApp Files (ANF) come storage connesso guest
* Cloud Volumes ONTAP (CVO) come storage connesso agli ospiti
* Azure NetApp Files (ANF) come datastore NFS supplementare


Visualizza il dettagliolink:azure-guest.html["opzioni di archiviazione di connessione ospite per AVS"] .  Visualizza il dettagliolink:azure-native-nfs-datastore-option.html["opzioni di datastore NFS supplementari per AVS"] .

--
.GCP / GCVE
--
Google Cloud supporta l'archiviazione NetApp nelle seguenti configurazioni:

* Cloud Volumes ONTAP (CVO) come storage connesso agli ospiti
* Google Cloud NetApp Volumes (NetApp Volumes) come storage connesso agli ospiti
* Google Cloud NetApp Volumes (NetApp Volumes) come datastore NFS supplementare


Visualizza il dettagliolink:gcp-guest.html["opzioni di archiviazione per la connessione degli ospiti per GCVE"] .  Visualizza il dettagliolink:gcp-ncvs-datastore.html["opzioni di datastore NFS supplementari per GCVE"] .

Per saperne di piùlink:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Supporto del datastore Google Cloud NetApp Volumes per Google Cloud VMware Engine (blog NetApp )"^] Olink:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Come utilizzare Google Cloud NetApp Volumes come datastore per Google Cloud VMware Engine (blog di Google)"^]

--
====