---
sidebar: sidebar 
permalink: vmware/vmw-azure-avs-overview.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Funzionalità NetApp per Azure AVS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri di più sulle funzionalità che NetApp apporta ad Azure VMware Solution (AVS): da NetApp come dispositivo di archiviazione connesso guest o come datastore NFS supplementare alla migrazione dei flussi di lavoro, all'estensione/bursting nel cloud, al backup/ripristino e al disaster recovery.

Passa alla sezione del contenuto desiderato selezionando tra le seguenti opzioni:

* link:#config["Configurazione di AVS in Azure"]
* link:#datastore["Opzioni di archiviazione NetApp per AVS"]
* link:#solutions["Soluzioni cloud NetApp /VMware"]




== Configurazione di AVS in Azure

Come per l'ambiente on-premise, la pianificazione di un ambiente di virtualizzazione basato su cloud è fondamentale per un ambiente di produzione di successo per la creazione di VM e la migrazione.

Questa sezione descrive come configurare e gestire Azure VMware Solution e come utilizzarla in combinazione con le opzioni disponibili per la connessione dello storage NetApp .


NOTE: L'archiviazione in-guest è l'unico metodo supportato per connettere Cloud Volumes ONTAP ad Azure VMware Solution.

Il processo di configurazione può essere suddiviso nei seguenti passaggi:

* Registra il fornitore di risorse e crea un cloud privato
* Connettiti a un gateway di rete virtuale ExpressRoute nuovo o esistente
* Convalida la connettività di rete e accedi al cloud privato


Visualizza il dettagliolink:../vmware/vmw-azure-avs-setup.html["passaggi di configurazione per AVS"] .



== Opzioni di archiviazione NetApp per AVS

Lo storage NetApp può essere utilizzato in diversi modi, come connessione Guess o come datastore NFS supplementare, all'interno di Azure AVS.

Per favore visitalink:vmw-hybrid-support-configs.html["Opzioni di archiviazione NetApp supportate"] per maggiori informazioni.

Azure supporta l'archiviazione NetApp nelle seguenti configurazioni:

* Azure NetApp Files (ANF) come storage connesso guest
* Cloud Volumes ONTAP (CVO) come storage connesso agli ospiti
* Azure NetApp Files (ANF) come datastore NFS supplementare


Visualizza il dettagliolink:../vmware/vmw-azure-avs-guest-storage.html["opzioni di archiviazione di connessione ospite per AVS"] . Visualizza il dettagliolink:../vmware/vmw-azure-avs-nfs-ds-config.html["opzioni di datastore NFS supplementari per AVS"] .



== Casi d'uso della soluzione

Con le soluzioni cloud NetApp e VMware, molti casi d'uso sono semplici da implementare in Azure AVS. Questi casi sono definiti per ciascuna delle aree cloud definite da VMware:

* Protezione (include sia Disaster Recovery che Backup/Ripristino)
* Estendere
* Migrare


link:vmw-azure-avs-solutions.html["Esplora le soluzioni NetApp per Azure AVS"]
