---
sidebar: sidebar 
permalink: google/gcp-gcnv-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Google Cloud NetApp Volumes espone più porte TCP per gestire condivisioni NFS e SMB. 
---
= Firewall
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes espone più porte TCP per gestire condivisioni NFS e SMB:

* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-nfs-clients#firewall_rules_for_nfs_volumes_access["Porte richieste per l'accesso NFS"^]
* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-smb-clients#firewall_rules_for_smb_volumes_access["Porte richieste per l'accesso SMB"^]


Inoltre, SMB, NFS con LDAP, incluso Kerberos, e le configurazioni a doppio protocollo richiedono l'accesso a un dominio Windows Active Directory. Le connessioni ad Active Directory devono essere https://docs.cloud.google.com/netapp/volumes/docs/configure-and-use/active-directory/create-ad-policy["configurato"^] configurate a livello di regione. I controller di dominio (DC) di Active Directory vengono identificati utilizzando https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04["Rilevamento DC basato su DNS"^] i server DNS specificati. Vengono utilizzati tutti i DC restituiti. L'elenco dei DC idonei può essere limitato specificando un sito di Active Directory.

Google Cloud NetApp Volumes si connette utilizzando indirizzi IP dell'intervallo CIDR assegnato con il comando `gcloud compute address` mentre https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/networking#configure_private_services_access["onboarding di Google Cloud NetApp Volumes"^]. Puoi usare questo CIDR come indirizzi di origine per configurare i firewall in entrata per i controller di dominio di Active Directory.

I controller di dominio di Active Directory devono https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/security-considerations["esporre le porte ai CIDR di Google Cloud NetApp Volumes come menzionato qui"^].
