---
sidebar: sidebar 
permalink: google/gcp-gcnv-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Google Cloud NetApp Volumes espone più porte TCP per gestire condivisioni NFS e SMB. 
---
= Firewall
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes espone più porte TCP per gestire condivisioni NFS e SMB:

* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Porte richieste per l'accesso NFS"^]
* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Porte richieste per l'accesso SMB"^]


Inoltre, le configurazioni SMB, NFS con LDAP incluso Kerberos e a doppio protocollo richiedono l'accesso a un dominio Windows Active Directory.  Le connessioni Active Directory devono essere https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes?hl=en_US["configurato"^] su base regionale.  I controller di dominio (DC) di Active Directory vengono identificati utilizzando https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04["Rilevamento DC basato su DNS"^] utilizzando i server DNS specificati.  Tutti i DC restituiti vengono utilizzati.  L'elenco dei DC idonei può essere limitato specificando un sito Active Directory.

Google Cloud NetApp Volumes raggiunge gli indirizzi IP dall'intervallo CIDR assegnato con `gcloud compute address` comando mentre https://cloud.google.com/architecture/partners/netapp-cloud-volumes/setting-up-private-services-access?hl=en_US["onboarding di Google Cloud NetApp Volumes"^] .  È possibile utilizzare questo CIDR come indirizzo di origine per configurare i firewall in ingresso nei controller di dominio Active Directory.

I controller di dominio Active Directory devono https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["esporre le porte ai CIDR di Google Cloud NetApp Volumes come menzionato qui"^] .
