---
sidebar: sidebar 
permalink: google/gcp-gcnv-security-overview.html 
keywords: secure, architecture, tenancy model, identity management, control plane, security hardening, encryption, zero trust, ransomware 
summary: Google Cloud NetApp Volumes in Google Cloud offre molteplici modi per proteggere i tuoi dati in modo nativo. 
---
= Come Google Cloud NetApp Volumes in Google Cloud protegge i tuoi dati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes in Google Cloud offre molteplici modi per proteggere i tuoi dati in modo nativo.



== Architettura sicura e modello di locazione

Google Cloud NetApp Volumes fornisce un'architettura sicura in Google Cloud segmentando la gestione dei servizi (piano di controllo) e l'accesso ai dati (piano dati) su endpoint diversi in modo che nessuno dei due possa avere un impatto sull'altro (vedere la sezionelink:gcp-gcnv-arch-detail.html["Architettura Google Cloud NetApp Volumes"] ).  Utilizza Google https://cloud.google.com/vpc/docs/private-services-access?hl=en_US["accesso ai servizi privati"^] (PSA) quadro per fornire il servizio.  Questo framework distingue tra il produttore del servizio, fornito e gestito da NetApp, e il consumatore del servizio, che è un Virtual Private Cloud (VPC) in un progetto del cliente, che ospita i client che desiderano accedere alle condivisioni file di Google Cloud NetApp Volumes .

In questa architettura, gli inquilini (vedere la sezionelink:gcp-gcnv-arch-detail.html#tenancy-model["Modello di locazione"] ) sono definiti come progetti Google Cloud completamente isolati l'uno dall'altro, a meno che non siano esplicitamente connessi dall'utente.  I tenant consentono l'isolamento completo dei volumi di dati, dei servizi di denominazione esterni e di altri elementi essenziali della soluzione dagli altri tenant utilizzando la piattaforma di volumi Google Cloud NetApp Volumes .  Poiché la piattaforma Google Cloud NetApp Volumes è connessa tramite peering VPC, anche a essa si applica tale isolamento.  È possibile abilitare la condivisione dei volumi Google Cloud NetApp Volumes tra più progetti utilizzando una VPC condivisa (vedere la sezionelink:gcp-gcnv-arch-detail.html#shared-vpcs["VPC condivise"] ).  È possibile applicare controlli di accesso alle condivisioni SMB e alle esportazioni NFS per limitare chi o cosa può visualizzare o modificare i set di dati.



== Gestione solida dell'identità per il piano di controllo

Nel piano di controllo in cui avviene la configurazione di Google Cloud NetApp Volumes , la gestione delle identità viene gestita utilizzando https://cloud.google.com/iam/docs/overview["Gestione dell'accesso all'identità (IAM)"^] .  IAM è un servizio standard che consente di controllare l'autenticazione (accessi) e l'autorizzazione (permessi) per le istanze dei progetti Google Cloud.  Tutta la configurazione viene eseguita con le API Google Cloud NetApp Volumes tramite un trasporto HTTPS sicuro utilizzando la crittografia TLS 1.2, mentre l'autenticazione viene eseguita tramite token JWT per una maggiore sicurezza.  L'interfaccia utente della console Google per Google Cloud NetApp Volumes traduce l'input dell'utente in chiamate API Google Cloud NetApp Volumes .



== Rafforzamento della sicurezza - Limitazione delle superfici di attacco

Una parte efficace della sicurezza consiste nel limitare il numero di superfici di attacco disponibili in un servizio.  Le superfici di attacco possono includere vari elementi, tra cui dati inattivi, trasferimenti in corso, accessi e gli stessi set di dati.

Un servizio gestito rimuove alcune delle superfici di attacco intrinsecamente previste dalla sua progettazione.  Gestione delle infrastrutture, come descritto nella sezionelink:gcp-gcnv-service-operation.html["Funzionamento del servizio,"] è gestito da un team dedicato ed è automatizzato per ridurre il numero di volte in cui un essere umano interviene effettivamente sulle configurazioni, il che contribuisce a ridurre il numero di errori intenzionali e non intenzionali.  La rete è isolata in modo che solo i servizi necessari possano accedere l'uno all'altro.  La crittografia è integrata nell'archiviazione dei dati e solo il piano dati necessita dell'attenzione degli amministratori Google Cloud NetApp Volumes in termini di sicurezza.  Nascondendo la maggior parte della gestione dietro un'interfaccia API, la sicurezza viene raggiunta limitando le superfici di attacco.



== Modello Zero Trust

Storicamente, la filosofia della sicurezza informatica è stata quella di fidarsi ma verificare, e si è manifestata affidandosi esclusivamente a meccanismi esterni (come firewall e sistemi di rilevamento delle intrusioni) per mitigare le minacce.  Tuttavia, attacchi e violazioni si sono evoluti per aggirare la verifica negli ambienti attraverso phishing, ingegneria sociale, minacce interne e altri metodi che forniscono la verifica per entrare nelle reti e creare scompiglio.

Zero Trust è diventato una nuova metodologia di sicurezza, il cui mantra attuale è "non fidarsi di nulla e verificare comunque tutto".  Pertanto, per impostazione predefinita, non è consentito alcun accesso.  Questo mantra viene applicato in vari modi, tra cui firewall standard e sistemi di rilevamento delle intrusioni (IDS), nonché con i seguenti metodi:

* Metodi di autenticazione avanzati (come i token Kerberos crittografati AES o JWT)
* Singole fonti solide di identità (ad esempio Windows Active Directory, Lightweight Directory Access Protocol (LDAP) e Google IAM)
* Segmentazione della rete e multitenancy sicura (solo gli inquilini hanno accesso per impostazione predefinita)
* Controlli di accesso granulari con criteri di accesso con privilegi minimi
* Piccoli elenchi esclusivi di amministratori dedicati e fidati con audit digitale e tracciabilità cartacea


Google Cloud NetApp Volumes in esecuzione su Google Cloud aderisce al modello Zero Trust implementando il principio "non fidarti di nulla, verifica tutto".



== Crittografia

Crittografare i dati a riposo (vedere la sezionelink:gcp-gcnv-data-encrypt-at-rest.html["Crittografia dei dati a riposo"] ) utilizzando cifrari XTS-AES-256 con NetApp Volume Encryption (NVE) e in volo conlink:gcp-gcnv-data-encrypt-in-transit.html#smb-encryption["Crittografia SMB"] o supporto NFS Kerberos 5p.  Puoi stare tranquillo sapendo che i trasferimenti di replica tra regioni sono protetti dalla crittografia TLS 1.2 (vedi la sezione link:gcp-gcnv-security-considerations.html#Rilevamento, prevenzione e mitigazione di ransomware, malware e virus#cross-region-replication["Replica tra regioni"]).  Inoltre, la rete Google fornisce anche comunicazioni crittografate (vedere la sezionelink:gcp-gcnv-data-encrypt-in-transit.html["Crittografia dei dati in transito"] ) per un ulteriore livello di protezione contro gli attacchi.  Per ulteriori informazioni sulla crittografia del trasporto, vedere la sezionelink:gcp-gcnv-data-encrypt-in-transit.html#google-cloud-network["Rete Google Cloud"] .



== Protezione dei dati e backup

La sicurezza non riguarda solo la prevenzione degli attacchi.  Riguarda anche il modo in cui ci riprendiamo dagli attacchi, se e quando si verificano.  Questa strategia include la protezione dei dati e i backup.  Google Cloud NetApp Volumes fornisce metodi per replicare in altre regioni in caso di interruzioni (vedere la sezionelink:gcp-gcnv-security-considerations.html#cross-region-replication["Replicazione interregionale"] ) o se un set di dati è stato colpito da un attacco ransomware.  Può anche eseguire backup asincroni dei dati in posizioni esterne all'istanza di Google Cloud NetApp Volumes utilizzandolink:gcp-gcnv-security-considerations.html#cloud-volumes-service-backup["Backup Google Cloud NetApp Volumes"] .  Con backup regolari, la mitigazione degli eventi di sicurezza può richiedere meno tempo, facendo risparmiare denaro e stress agli amministratori.



== Mitigazione rapida del ransomware con copie Snapshot leader del settore

Oltre alla protezione dei dati e ai backup, Google Cloud NetApp Volumes fornisce supporto per copie Snapshot immutabili (vedere la sezionelink:gcp-gcnv-security-considerations.html#immutable-snapshot-copies["Copie Snapshot immutabili"] ) di volumi che consentono il ripristino da attacchi ransomware (vedere la sezionelink:gcp-gcnv-service-operation.html["Funzionamento del servizio"] ) entro pochi secondi dalla scoperta del problema e con il minimo disagio.  I tempi e gli effetti del ripristino dipendono dalla pianificazione degli snapshot, ma è possibile creare copie snapshot che forniscono un delta di appena un'ora negli attacchi ransomware.  Le copie snapshot hanno un effetto trascurabile sulle prestazioni e sull'utilizzo della capacità e rappresentano un approccio a basso rischio e ad alto rendimento per proteggere i set di dati.
