---
sidebar: sidebar 
permalink: videos/hmc-aws-videos.html 
summary: Video e demo che mostrano le soluzioni multicloud ibride AWS con NetApp 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= Guarda i video sulle soluzioni multicloud ibride per Amazon Web Services con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esplora la libreria video completa di NetApp con soluzioni multicloud ibride per AWS con NetApp.  Guarda i video sullo storage connesso agli ospiti, sui risparmi sul costo totale di proprietà, sugli archivi dati supplementari e sui flussi di lavoro di migrazione per VMware Cloud on AWS e Amazon FSx for ONTAP, inclusi gli scenari Windows e Linux.



== Archiviazione connessa agli ospiti

.Archiviazione connessa guest Windows con FSx ONTAP tramite iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Archiviazione connessa guest Linux con FSx ONTAP tramite NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]


== TCO e datastore supplementari

.Risparmio sul TCO di VMware Cloud su AWS con Amazon FSx ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Datastore supplementare VMware Cloud su AWS con Amazon FSx ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]


== Flussi di lavoro di migrazione (HCX)

.Configurazione e distribuzione di VMware HCX per VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Dimostrazione di migrazione vMotion con VMware HCX per VMC e FSx ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Dimostrazione di migrazione a freddo con VMware HCX per VMC e FSx ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]